#!/bin/bash
# init_project.sh - Initialize a new multi-ai-workflow project
# Usage: init_project.sh <project-name> [base-path]

set -e

PROJECT_NAME="$1"
BASE_PATH="${2:-.}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE_DIR="$(dirname "$SCRIPT_DIR")/templates"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
error() {
    echo -e "${RED}Error: $1${NC}" >&2
    exit 1
}

success() {
    echo -e "${GREEN}$1${NC}"
}

info() {
    echo -e "${YELLOW}$1${NC}"
}

# Validate project name
if [ -z "$PROJECT_NAME" ]; then
    error "Project name is required.\nUsage: $0 <project-name> [base-path]"
fi

# Validate project name format (alphanumeric, hyphens, underscores)
if ! [[ "$PROJECT_NAME" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    error "Project name must contain only alphanumeric characters, hyphens, and underscores."
fi

# Resolve base path
if [ "$BASE_PATH" = "." ]; then
    BASE_PATH="$PWD"
fi

TARGET_DIR="$BASE_PATH/$PROJECT_NAME"

# Check if target directory already exists
if [ -d "$TARGET_DIR" ]; then
    error "Directory '$TARGET_DIR' already exists."
fi

info "Initializing project: $PROJECT_NAME"
info "Location: $TARGET_DIR"

# Create directory structure
info "Creating directory structure..."
mkdir -p "$TARGET_DIR"/{docs/reviews,code,.workflow}

# Copy and process README template
info "Creating README.md..."
if [ -f "$TEMPLATE_DIR/README.template.md" ]; then
    cat "$TEMPLATE_DIR/README.template.md" | sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" > "$TARGET_DIR/README.md"
else
    error "Template file not found: $TEMPLATE_DIR/README.template.md"
fi

# Copy gitignore
info "Creating .gitignore..."
if [ -f "$TEMPLATE_DIR/gitignore.template" ]; then
    cp "$TEMPLATE_DIR/gitignore.template" "$TARGET_DIR/.gitignore"
else
    error "Template file not found: $TEMPLATE_DIR/gitignore.template"
fi

# Copy and process workflow config
info "Creating .workflow-config.yaml..."
if [ -f "$TEMPLATE_DIR/workflow-config.template.yaml" ]; then
    cat "$TEMPLATE_DIR/workflow-config.template.yaml" | sed "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" > "$TARGET_DIR/.workflow-config.yaml"
else
    error "Template file not found: $TEMPLATE_DIR/workflow-config.template.yaml"
fi

# Create placeholder files
info "Creating placeholder documentation files..."
cat > "$TARGET_DIR/docs/requirements.md" << 'EOF'
# Requirements Specification

> This file will be generated by the workflow. You can also write your requirements here manually.

## Overview

[Project overview and goals]

## Functional Requirements

### Feature 1
- Description
- Acceptance criteria

## Non-Functional Requirements

- Performance
- Security
- Scalability

## Constraints

[Technical and business constraints]
EOF

cat > "$TARGET_DIR/docs/design.md" << 'EOF'
# Design Document

> This file will be generated by the workflow. You can also write your design here manually.

## Architecture

[High-level architecture description]

## Technology Stack

[List of technologies and frameworks]

## Modules

[Module descriptions]

## Data Model

[Database schema, data structures]

## Interfaces

[APIs, external integrations]
EOF

# Initialize git repository
info "Initializing git repository..."
cd "$TARGET_DIR"
git init --quiet
git add .
git commit --quiet -m "Initial commit: project structure created by multi-ai-workflow-cli"

# Output success message
success "\n✓ Project initialized successfully!"
echo ""
echo "Project structure:"
echo "  $TARGET_DIR/"
echo "  ├── docs/"
echo "  │   ├── requirements.md"
echo "  │   ├── design.md"
echo "  │   └── reviews/"
echo "  ├── code/"
echo "  ├── .workflow/"
echo "  ├── README.md"
echo "  ├── .gitignore"
echo "  └── .workflow-config.yaml"
echo ""
echo "Next steps:"
echo "  1. cd $TARGET_DIR"
echo "  2. Review and edit docs/requirements.md"
echo "  3. Run /workflow-start to begin the workflow"
echo ""

# Output the target directory path for the caller
echo "$TARGET_DIR"
